version: '3'

services:
  nginx-phpfpm:
    build:
      args:
        - TARGETARCH=amd64
      context: .
    image: localhost/alpine-nginx-phpfpm
    ports:
      - 8080:80
    volumes:
      - ./php:/var/www
